version: '3'
services:
        web:
                image: flask_finalcptperiod4_v1
                build: .
                ports:
                        - "8753:8753"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped