version: '3'
services:
      web:
              image: flask_finalcptperiod4_v1
              build: .
              ports:
                      - "8067:8080"
              volumes:
                      - persistent_volume:/app/volumes
volumes:
persistent_volume:
  driver: local
  driver_opts:
    o: bind
    type: none
    device: /home/ubuntu/finalcptperiod4/volumes
    # replace just flask_portfolio